language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t jpmc9005/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jpmc9005/react-test npm test

after_success:
    - docker build -t jpmc9005/multi-client ./client
    - docker build -t jpmc9005/multi-nginx ./nginx
    - docker build -t jpmc9005/multi-server ./server
    - docker build -t jpmc9005/multi-worker ./worker
    # log in to the docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # push the images to docker hub
    - docker push jpmc9005/multi-client
    - docker push jpmc9005/multi-nginx
    - docker push jpmc9005/multi-server
    - docker push jpmc9005/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: eu-west-3 
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-west-3-709982155892
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY